name: Path filtering
description: GitHub Action that filters paths.
branding:
  icon: folder
  color: blue
runs:
  using: 'node12'
  main:  'dist/index.js'
inputs:
  baseRef:
    description: Ref to the base.
  headRef:
    description: Ref to the head.
  paths:
    description: YAML-formatted string with the path pattern matchers.
